[package]
name = "trymoveme_rooms"
version = "0.0.1"

[addresses]
trymoveme = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
